# Generated by Django 3.1.4 on 2020-12-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=50)),
                ('vaccine_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateTimeField(verbose_name='shipment received')),
                ('doses', models.IntegerField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontend.vaccinemanufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateTimeField(verbose_name='dose date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontend.patient')),
            ],
        ),
    ]
