# Generated by Django 3.1.4 on 2020-12-13 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineshipment',
            name='receive_date',
        ),
        migrations.AddField(
            model_name='vaccinemanufacturer',
            name='days_between_doses',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccineshipment',
            name='expected_receive_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='expected receive date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccineshipment',
            name='received_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='shipment received'),
            preserve_default=False,
        ),
    ]
